### ISSUE TITLE
todo tomorrow

### ISSUE THREAD

**Issue by rissole** [rissole/allaboutthebenjamins#1]
- [x] title screen - all about the benjamins
- [x] nicely formatted score
- [x] readable text
- [x] alan powerup
- [x] moneybook and sharepoint enemies
- [x] 'thank you for evaluating' (win) screen
